baseURL = 'https://preview.axiomat.io/'
languageCode = 'en-us'
title = 'Axiomat — High-value software, low-friction experiences'
theme = "axiom"
enableRobotsTXT = true
description = "Axiomat is a software and technology company building products that do more and ask less. After years helping the world's largest teams deliver at scale, we're building software of our own — starting with Ward, our flagship product."

[params.meta]
favicon = true
