baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 40

[[menus.main]]
name = 'Events'
pageRef = '/events'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
